name: deskovka_server
version: 0.0.1
description: A minimal web server using the shelf package.
environment:
  sdk: '>=1.0.0 <2.0.0'
dependencies:
  args: '>=0.10.0 <0.13.0'
  deskovka_libs:
    path: ../deskovka_libs/
  mime: any
  shelf: any
  shelf_route: any
  shelf_simple_session: any
  shelf_web_socket: any
  html: any
  shelf_static:
    path: C:\Users\Tal\Documents\GitHub\shelf_static.dart
