name: deskovka_client
version: 0.0.1
description: An absolute bare-bones web app.
environment:
  sdk: '>=1.0.0 <2.0.0'
dependencies:
  browser: any
  deskovka_libs:
    path: ../deskovka_libs
  mustache_no_mirror: any
  ui:
    path: ../ui
