name: ui
description: >
  A library useful for applications or for sharing on pub.dartlang.org.
version: 0.0.1
#author: <your name> <email@example.com>
#homepage: https://www.example.com
#dependencies:
#  lib_name: any
dev_dependencies:
  unittest: any
  mustache_no_mirror: any
  deskovka_libs:
    path: ../deskovka_libs/